version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    expose:
      - 5672
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      MONGO_URI: 'mongodb://mongodb:27017'
      RABBITMQ_URI: 'amqp://user:password@localhost:5672'
      PORT: 80
